<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>VariableFleaPrices</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <Version>3.0.0</Version>

    <OutputPath>bin\$(Configuration)\$(AssemblyName)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Configurations>Debug;Release;Package</Configurations>

    <SPTDir Condition="'$(SPTDir)' == ''">D:\SPT-5.0.0-47242-BE\SPT_Runtime\</SPTDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Package'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Package\**" />
    <Content Remove="Package\**" />
    <EmbeddedResource Remove="Package\**" />
    <None Remove="Package\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SPTarkov.Common">
      <HintPath>$(SPTDir)SPTarkov.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SPTarkov.DI">
      <HintPath>$(SPTDir)SPTarkov.DI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SPTarkov.Reflection">
      <HintPath>$(SPTDir)SPTarkov.Reflection.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SPTarkov.Server.Core">
      <HintPath>$(SPTDir)SPTarkov.Server.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SemanticVersioning">
      <HintPath>$(SPTDir)SemanticVersioning.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /i /s /e /y &quot;$(OutDir)&quot; &quot;$(SPTDir)user\mods\$(AssemblyName)&quot;" />
  </Target>

</Project>